version: '3'
services: 
    hugo:
        image: klakegg/hugo:0.83.1-ubuntu
        container_name: blog-hugo
        volumes:
            - ".:/src"
        entrypoint: bash
        ports:
            - "1313:1313"
        tty: true
        working_dir: /src/blog

    php:
        container_name: blog-php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./php:/php
            - ./blog:/blog
            - ./docs:/docs
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /php
        tty: true
